name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Hello World
        run: echo "Hello World"

      - name: Install Dependencies
        run: |
          npm install

      - name: Run Tests
        run: |
          npm test -- --watchAll=false

      - name: Build Application
        run: |
          npm run build
